### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by RanyAlbegWein**
Update dependencies in Spring Initializr URL from 'cloud-gateway' to 'cloud-gateway-reactive' to support the RouteLocator demonstrated in the code.

### CODE REVIEW

**Comment by robertmcnees** [comment]
Hi @RanyAlbegWein.  Thank you for the PR!  Good catch that the link to start.spring.io grabs the wrong dependencies.

Can you update the PR to also change the text in [this line](https://github.com/spring-guides/gs-gateway/blob/28de9b7b8b45130d6309328e3d2cdf5c62abe19b/README.adoc?plain=1#L29C36-L29C43)? The guide references `Gateway` when it should now reference `Reactive Gateway`.

For reference, this change was made for Boot 3.2 and later. The details are discussed in [this issue](https://github.com/spring-io/start.spring.io/issues/1367#issuecomment-1845505660) in the Spring Initilizr repository. When you use Boot 3.2 or later, adding the `Gateway` dependency will pull in `spring-cloud-starter-gateway-mvc` instead of the previous `spring-cloud-starter-gateway`.

**Comment by robertmcnees** [comment]
Additionally, you could remove this parameter from the link:

`&jvmVersion=11`

Java 11 is not a valid selection so Spring Initializr defaults to 17 anyhow.  Removing it completely will let Spring Initializr select the version, which is the desired behavior.

**Comment by RanyAlbegWein** [comment]
Thank you for the review! Modified as per your request.

**Comment by robertmcnees** [comment]
Thank you for the contribution!

**Comment by RanyAlbegWein** [comment]
You're welcome! Happy to give back!

**Pull request merged**
